name: prlab_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  prlab_commons:
    path: ../prlab_commons

  serverpod_client: ^1.1.1
  serverpod_auth_client: ^1.1.1