name: prlab_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  serverpod_client: ^1.1.1
  serverpod_auth_client: ^1.1.1
  dart_mappable: ^3.1.3
dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^3.2.0
