name: prlab_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  serverpod_flutter: ^1.1.1
  serverpod_auth_shared_flutter: ^1.1.1
  serverpod_auth_email_flutter: ^1.1.1
  prlab_client:
    path: ../prlab_client

  full_responsive:
    path: ./full_responsive
  cupertino_icons: ^1.0.5
  flutter_dotenv: ^5.1.0
  auto_route: ^7.7.1


dev_dependencies:
  bloc_test: ^9.1.2
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - stg.env
    - dev.env
    - prod.env
  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/fonts/Montserrat-Regular.ttf

full_responsive:
  resolutions:
    - name: "mobile"
      width: 390
      height: 844
    - name: "desktop"
      width: 1280
      height: 720