name: prlab_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  serverpod_flutter: ^1.1.1
  serverpod_auth_email_flutter: ^1.1.1
  serverpod_auth_client:

  #calendario
  calendar_date_picker2: ^0.5.3

  #data persistence
  isar: ^4.0.0-dev.9
  isar_flutter_libs: ^4.0.0-dev.9
  path_provider: ^2.1.1
  localstorage: ^4.0.0+1

  prlab_client:
    path: ../prlab_client

  full_responsive:
    path: ./full_responsive
  cupertino_icons: ^1.0.5
  flutter_dotenv: ^5.1.0
  auto_route: ^7.7.1

  assets_gen: ^1.5.0
  url_launcher: ^6.1.12
  image_picker: ^0.8.7
  shimmer: ^3.0.0
  fl_chart: ^0.63.0
  flutter_quill: ^7.4.7
  flutter_quill_extensions: ^0.4.1
  file_picker: ^5.5.0

dev_dependencies:
  auto_route_generator: ^7.2.0
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - stg.env
    - dev.env
    - prod.env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf

full_responsive:
  resolutions:
    - name: "mobile"
      width: 390
      height: 844
    - name: "desktop"
      width: 1280
      height: 832
