
apiServer:
  port: 8080
  publicHost: api.examplepod.com
  publicPort: 443
  publicScheme: https


insightsServer:
  port: 8081
  publicHost: insights.examplepod.com
  publicPort: 443
  publicScheme: https


webServer:
  port: 8082
  publicHost: app.examplepod.com
  publicPort: 443
  publicScheme: https


database:
  host: database.private-production.examplepod.com
  port: 5432
  name: serverpod
  user: postgres

redis:
  enabled: false
  host: redis.private-production.examplepod.com
  port: 6379
