apiServer: 
  port: 8080
  publicHost: 0.0.0.0
  publicPort: 8080
  publicScheme: http
insightsServer: 
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http
webServer: 
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http
database: 
  host: db.fytajeinqwkiuvyozibk.supabase.co
  port: 5432
  name: postgres
  user: postgres
  password: nWYCK59DiprYNNWc
redis: 
  enabled: false
  host: redis.private-staging.examplepod.com
  port: 6379
