name: prlab_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  cloudinary: ^1.2.0
  dart_jsonwebtoken: ^2.8.2
  dart_mappable: ^3.1.3
  dio: ^5.3.2
  logging: ^1.2.0
  mailer: ^6.0.1
  serverpod: ^1.1.1
  serverpod_auth_server: ^1.1.1
  similar_web:
    path: ../../similar_web
  yaml_writer: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^3.2.0
  lints: ^2.0.1
