// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 20.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'prlab_flutter';

  static const String assets_icons_apartment_png = 'assets/icons/apartment.png';
  static const String prlab_flutter$assets_icons_apartment_png = 'packages/prlab_flutter/assets/icons/apartment.png';

  static const String assets_icons_base_de_datos_png = 'assets/icons/base_de_datos.png';
  static const String prlab_flutter$assets_icons_base_de_datos_png = 'packages/prlab_flutter/assets/icons/base_de_datos.png';

  static const String assets_icons_conocimiento_de_la_marca_png = 'assets/icons/conocimiento de la marca.png';
  static const String prlab_flutter$assets_icons_conocimiento_de_la_marca_png = 'packages/prlab_flutter/assets/icons/conocimiento de la marca.png';

  static const String assets_icons_contrato_png = 'assets/icons/contrato.png';
  static const String prlab_flutter$assets_icons_contrato_png = 'packages/prlab_flutter/assets/icons/contrato.png';

  static const String assets_icons_leaderboard_png = 'assets/icons/leaderboard.png';
  static const String prlab_flutter$assets_icons_leaderboard_png = 'packages/prlab_flutter/assets/icons/leaderboard.png';

  static const String assets_icons_link_png = 'assets/icons/link.png';
  static const String prlab_flutter$assets_icons_link_png = 'packages/prlab_flutter/assets/icons/link.png';

  static const String assets_icons_logo_png = 'assets/icons/logo.png';
  static const String prlab_flutter$assets_icons_logo_png = 'packages/prlab_flutter/assets/icons/logo.png';

  static const String assets_icons_metricas_png = 'assets/icons/metricas.png';
  static const String prlab_flutter$assets_icons_metricas_png = 'packages/prlab_flutter/assets/icons/metricas.png';

  static const String assets_icons_no_hay_conversaciones_recientes_png = 'assets/icons/no_hay_conversaciones_recientes.png';
  static const String prlab_flutter$assets_icons_no_hay_conversaciones_recientes_png = 'packages/prlab_flutter/assets/icons/no_hay_conversaciones_recientes.png';

  static const String assets_icons_otras_casas_png = 'assets/icons/otras_casas.png';
  static const String prlab_flutter$assets_icons_otras_casas_png = 'packages/prlab_flutter/assets/icons/otras_casas.png';

  static const String assets_icons_signos_vitales_png = 'assets/icons/signos_vitales.png';
  static const String prlab_flutter$assets_icons_signos_vitales_png = 'packages/prlab_flutter/assets/icons/signos_vitales.png';

  static const String assets_images_avion_de_papel_png = 'assets/images/avion_de_papel.png';
  static const String prlab_flutter$assets_images_avion_de_papel_png = 'packages/prlab_flutter/assets/images/avion_de_papel.png';

  static const String assets_images_diario_png = 'assets/images/diario.png';
  static const String prlab_flutter$assets_images_diario_png = 'packages/prlab_flutter/assets/images/diario.png';

  static const String assets_images_mano_saludando_png = 'assets/images/mano_saludando.png';
  static const String prlab_flutter$assets_images_mano_saludando_png = 'packages/prlab_flutter/assets/images/mano_saludando.png';

  static const String assets_images_nada_para_ver_png = 'assets/images/nada_para_ver.png';
  static const String prlab_flutter$assets_images_nada_para_ver_png = 'packages/prlab_flutter/assets/images/nada_para_ver.png';

  static const String assets_images_opacidad_png = 'assets/images/opacidad.png';
  static const String prlab_flutter$assets_images_opacidad_png = 'packages/prlab_flutter/assets/images/opacidad.png';

  static const String assets_images_subrayado_png = 'assets/images/subrayado.png';
  static const String prlab_flutter$assets_images_subrayado_png = 'packages/prlab_flutter/assets/images/subrayado.png';

  static const String dev_env = 'dev.env';
  static const String prlab_flutter$dev_env = 'packages/prlab_flutter/dev.env';

  static const String prod_env = 'prod.env';
  static const String prlab_flutter$prod_env = 'packages/prlab_flutter/prod.env';

  static const String stg_env = 'stg.env';
  static const String prlab_flutter$stg_env = 'packages/prlab_flutter/stg.env';
}
