name: full_responsive
description: The ultimate solution for running your Flutter App in every screen size/resolution/ratio through the easiest/leanest design-development workflow possible.
version: 0.1.0
repository: https://github.com/Rodsevich/full_responsive
homepage: https://gitlab.com/Rodsevich/full_responsive

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  build: ^2.3.0
  build_config: ^1.1.0
  dart_style: ^2.2.3
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  glob: ^2.1.0
  mustachex: ^0.1.1
  path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  test: ^1.16.0
